// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Brand Color documents
 */
interface BrandColorDocumentData {
  /**
   * Name field in *Brand Color*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_color.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Value field in *Brand Color*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_color.value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  value: prismic.ColorField;
}

/**
 * Brand Color document from Prismic
 *
 * - **API ID**: `brand_color`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandColorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BrandColorDocumentData>,
    "brand_color",
    Lang
  >;

/**
 * Item in *Footer → Nav Links*
 */
export interface FooterDocumentDataNavLinksItem {
  /**
   * Label field in *Footer → Nav Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.nav_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Footer → Nav Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.nav_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Social*
 */
export interface FooterDocumentDataSocialItem {
  /**
   * Service field in *Footer → Social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].service
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  service: prismic.SelectField<
    | "Twitter"
    | "Instagram"
    | "GitHub"
    | "LinkedIn"
    | "Facebook"
    | "TikTok"
    | "YouTube"
  >;

  /**
   * URL field in *Footer → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Brand Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.brand_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_text: prismic.KeyTextField;

  /**
   * Nav Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.nav_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_links: prismic.GroupField<Simplify<FooterDocumentDataNavLinksItem>>;

  /**
   * Legal Rich Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_rich_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  legal_rich_text: prismic.RichTextField;

  /**
   * Social field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social: prismic.GroupField<Simplify<FooterDocumentDataSocialItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | HeadlineCtaCenteredSlice
  | FaqWithHeadingSlice
  | TestimonialsSlice
  | FeaturedProjectsSlice
  | ServicesCarouselSlice
  | SplitContentSlice
  | HeroPixelArtSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type ProjectPostDocumentDataSlicesSlice =
  | HeadlineCtaCenteredSlice
  | TestimonialWithAvatarSlice
  | ImageCarouselSlice
  | ProcessWithImageStepsSlice
  | ProjectSummaryShowcaseSlice
  | HeroShowcaseSlice;

/**
 * Content for Project Post documents
 */
interface ProjectPostDocumentData {
  /**
   * Project Title field in *Project Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Excerpt field in *Project Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Project Date field in *Project Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.project_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  project_date: prismic.DateField;

  /**
   * Client Name field in *Project Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.client_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField;

  /**
   * Featured field in *Project Post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project_post.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Slice Zone field in *Project Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Project Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project Post document from Prismic
 *
 * - **API ID**: `project_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectPostDocumentData>,
    "project_post",
    Lang
  >;

type ProjectsDocumentDataSlicesSlice =
  | ProjectsGridSlice
  | HeadlineCtaCenteredSlice;

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice> /**
   * Meta Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Content for Service Card documents
 */
interface ServiceCardDocumentData {
  /**
   * Title field in *Service Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *Service Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Color field in *Service Card*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Link field in *Service Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Service Card document from Prismic
 *
 * - **API ID**: `service_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceCardDocumentData>,
    "service_card",
    Lang
  >;

type ServicePostDocumentDataSlicesSlice = never;

/**
 * Content for Service Post documents
 */
interface ServicePostDocumentData {
  /**
   * Slice Zone field in *Service Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServicePostDocumentDataSlicesSlice> /**
   * Meta Title field in *Service Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service Post document from Prismic
 *
 * - **API ID**: `service_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicePostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicePostDocumentData>,
    "service_post",
    Lang
  >;

type ServicesDocumentDataSlicesSlice = HeadlineCtaIntroSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Technology documents
 */
interface TechnologyDocumentData {
  /**
   * Name field in *Technology*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technology.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Logo field in *Technology*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: technology.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TechnologyDocumentData>,
    "technology",
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Quote field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Avatar field in *Testimonial*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  avatar: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Color field in *Testimonial*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Company field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Rating field in *Testimonial*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;

  /**
   * Featured field in *Testimonial*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonial.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | BrandColorDocument
  | FooterDocument
  | HomepageDocument
  | ProjectPostDocument
  | ProjectsDocument
  | ServiceCardDocument
  | ServicePostDocument
  | ServicesDocument
  | SettingsDocument
  | TechnologyDocument
  | TestimonialDocument;

/**
 * Item in *FaqWithHeading → Default → Primary → FAQ Items*
 */
export interface FaqWithHeadingSliceDefaultPrimaryFaqItemsItem {
  /**
   * Question field in *FaqWithHeading → Default → Primary → FAQ Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_heading.default.primary.faq_items[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *FaqWithHeading → Default → Primary → FAQ Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_heading.default.primary.faq_items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqWithHeading → Default → Primary*
 */
export interface FaqWithHeadingSliceDefaultPrimary {
  /**
   * Background Color field in *FaqWithHeading → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_heading.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  background_color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Heading field in *FaqWithHeading → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_heading.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * FAQ Items field in *FaqWithHeading → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_with_heading.default.primary.faq_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq_items: prismic.GroupField<
    Simplify<FaqWithHeadingSliceDefaultPrimaryFaqItemsItem>
  >;
}

/**
 * Default variation for FaqWithHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading followed by a vertically stacked list of FAQs, each with question and optional answer.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqWithHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqWithHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqWithHeading*
 */
type FaqWithHeadingSliceVariation = FaqWithHeadingSliceDefault;

/**
 * FaqWithHeading Shared Slice
 *
 * - **API ID**: `faq_with_heading`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqWithHeadingSlice = prismic.SharedSlice<
  "faq_with_heading",
  FaqWithHeadingSliceVariation
>;

/**
 * Primary content in *FeaturedProjects → Default → Primary*
 */
export interface FeaturedProjectsSliceDefaultPrimary {
  /**
   * Heading field in *FeaturedProjects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Use Latest When Empty field in *FeaturedProjects → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: featured_projects.default.primary.use_latest_when_empty
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_latest_when_empty: prismic.BooleanField;

  /**
   * Project field in *FeaturedProjects → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.default.primary.project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [
      {
        id: "project_post";
        fields: [
          "project_title",
          "excerpt",
          "project_date",
          "client_name",
          "featured",
          "meta_title",
          "meta_description",
          "meta_image",
        ];
      },
    ]
  >;
}

/**
 * Default variation for FeaturedProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedProjects*
 */
type FeaturedProjectsSliceVariation = FeaturedProjectsSliceDefault;

/**
 * FeaturedProjects Shared Slice
 *
 * - **API ID**: `featured_projects`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProjectsSlice = prismic.SharedSlice<
  "featured_projects",
  FeaturedProjectsSliceVariation
>;

/**
 * Primary content in *HeadlineCtaCentered → Default → Primary*
 */
export interface HeadlineCtaCenteredSliceDefaultPrimary {
  /**
   * Background Color field in *HeadlineCtaCentered → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_centered.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  background_color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Headline field in *HeadlineCtaCentered → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_centered.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subtitle field in *HeadlineCtaCentered → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_centered.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Call To Action field in *HeadlineCtaCentered → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_centered.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HeadlineCtaCentered Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with headline, styled subtitle, and a single centered call-to-action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineCtaCenteredSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineCtaCenteredSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineCtaCentered*
 */
type HeadlineCtaCenteredSliceVariation = HeadlineCtaCenteredSliceDefault;

/**
 * HeadlineCtaCentered Shared Slice
 *
 * - **API ID**: `headline_cta_centered`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineCtaCenteredSlice = prismic.SharedSlice<
  "headline_cta_centered",
  HeadlineCtaCenteredSliceVariation
>;

/**
 * Primary content in *HeadlineCtaIntro → Default → Primary*
 */
export interface HeadlineCtaIntroSliceDefaultPrimary {
  /**
   * Headline field in *HeadlineCtaIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_intro.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * CTA Buttons field in *HeadlineCtaIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_intro.default.primary.cta_buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "solid" | "outline" | "ghost" | "link"
    >
  >;

  /**
   * Description field in *HeadlineCtaIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_intro.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeadlineCtaIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with a headline, a row of prominent call-to-action buttons, and a short intro text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineCtaIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineCtaIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineCtaIntro*
 */
type HeadlineCtaIntroSliceVariation = HeadlineCtaIntroSliceDefault;

/**
 * HeadlineCtaIntro Shared Slice
 *
 * - **API ID**: `headline_cta_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineCtaIntroSlice = prismic.SharedSlice<
  "headline_cta_intro",
  HeadlineCtaIntroSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroPixelArt → Default → Primary*
 */
export interface HeroPixelArtSliceDefaultPrimary {
  /**
   * First Line field in *HeroPixelArt → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_pixel_art.default.primary.first_line
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_line: prismic.KeyTextField;

  /**
   * Second Line field in *HeroPixelArt → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_pixel_art.default.primary.second_line
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  second_line: prismic.KeyTextField;

  /**
   * Decorative Image field in *HeroPixelArt → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_pixel_art.default.primary.graphic
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  graphic: prismic.ImageField<never>;

  /**
   * Primary Action Button field in *HeroPixelArt → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_pixel_art.default.primary.primary_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "solid" | "outline" | "ghost" | "link"
  >;

  /**
   * Secondary Action Button field in *HeroPixelArt → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_pixel_art.default.primary.secondary_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "solid" | "outline" | "ghost" | "link"
  >;
}

/**
 * Default variation for HeroPixelArt Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default layout with main headline, two action buttons, and pixel art/decorative imagery.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroPixelArtSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroPixelArtSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroPixelArt*
 */
type HeroPixelArtSliceVariation = HeroPixelArtSliceDefault;

/**
 * HeroPixelArt Shared Slice
 *
 * - **API ID**: `hero_pixel_art`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroPixelArtSlice = prismic.SharedSlice<
  "hero_pixel_art",
  HeroPixelArtSliceVariation
>;

/**
 * Item in *HeroShowcase → With Comparison Visual → Primary → Tech Stack Badges*
 */
export interface HeroShowcaseSliceWithComparisonVisualPrimaryTechStackItem {
  /**
   * Logo field in *HeroShowcase → With Comparison Visual → Primary → Tech Stack Badges*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_showcase.with_comparison_visual.primary.tech_stack[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroShowcase → With Comparison Visual → Primary*
 */
export interface HeroShowcaseSliceWithComparisonVisualPrimary {
  /**
   * Title field in *HeroShowcase → With Comparison Visual → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_showcase.with_comparison_visual.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroShowcase → With Comparison Visual → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_showcase.with_comparison_visual.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Tech Stack Badges field in *HeroShowcase → With Comparison Visual → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_showcase.with_comparison_visual.primary.tech_stack[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tech_stack: prismic.GroupField<
    Simplify<HeroShowcaseSliceWithComparisonVisualPrimaryTechStackItem>
  >;

  /**
   * Device Mockup field in *HeroShowcase → With Comparison Visual → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_showcase.with_comparison_visual.primary.device_mockup
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  device_mockup: prismic.ImageField<never>;
}

/**
 * With Comparison Visual variation for HeroShowcase Slice
 *
 * - **API ID**: `with_comparison_visual`
 * - **Description**: A hero section that highlights a key heading, subheading, tech stack display, and a side-by-side 'bad vs good' visual within a device frame.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroShowcaseSliceWithComparisonVisual =
  prismic.SharedSliceVariation<
    "with_comparison_visual",
    Simplify<HeroShowcaseSliceWithComparisonVisualPrimary>,
    never
  >;

/**
 * Slice variation for *HeroShowcase*
 */
type HeroShowcaseSliceVariation = HeroShowcaseSliceWithComparisonVisual;

/**
 * HeroShowcase Shared Slice
 *
 * - **API ID**: `hero_showcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroShowcaseSlice = prismic.SharedSlice<
  "hero_showcase",
  HeroShowcaseSliceVariation
>;

/**
 * Item in *ImageCarousel → Default → Primary → Slides*
 */
export interface ImageCarouselSliceDefaultPrimarySlidesItem {
  /**
   * Image field in *ImageCarousel → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.slides[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageCarousel → Default → Primary*
 */
export interface ImageCarouselSliceDefaultPrimary {
  /**
   * Slides field in *ImageCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  slides: prismic.GroupField<
    Simplify<ImageCarouselSliceDefaultPrimarySlidesItem>
  >;

  /**
   * Show Navigation Controls field in *ImageCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.show_navigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_navigation: prismic.BooleanField;
}

/**
 * Default variation for ImageCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Three-image landscape carousel with navigation arrows.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCarousel*
 */
type ImageCarouselSliceVariation = ImageCarouselSliceDefault;

/**
 * ImageCarousel Shared Slice
 *
 * - **API ID**: `image_carousel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCarouselSlice = prismic.SharedSlice<
  "image_carousel",
  ImageCarouselSliceVariation
>;

/**
 * Primary content in *People → Default → Primary*
 */
export interface PeopleSliceDefaultPrimary {
  /**
   * Headshot field in *People → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.headshot
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  headshot: prismic.ImageField<never>;

  /**
   * Name field in *People → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *People → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Details field in *People → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.default.primary.details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  details: prismic.KeyTextField;
}

/**
 * Default variation for People Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PeopleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PeopleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *People*
 */
type PeopleSliceVariation = PeopleSliceDefault;

/**
 * People Shared Slice
 *
 * - **API ID**: `people`
 * - **Description**: People
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PeopleSlice = prismic.SharedSlice<"people", PeopleSliceVariation>;

/**
 * Item in *ProcessWithImageSteps → Default → Primary → Images*
 */
export interface ProcessWithImageStepsSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *ProcessWithImageSteps → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *ProcessWithImageSteps → Default → Primary → Steps*
 */
export interface ProcessWithImageStepsSliceDefaultPrimaryStepsItem {
  /**
   * Step Heading field in *ProcessWithImageSteps → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.steps[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ProcessWithImageSteps → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ProcessWithImageSteps → Default → Primary*
 */
export interface ProcessWithImageStepsSliceDefaultPrimary {
  /**
   * Background Color field in *ProcessWithImageSteps → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  background_color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Heading field in *ProcessWithImageSteps → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sub Heading field in *ProcessWithImageSteps → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * Images field in *ProcessWithImageSteps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<ProcessWithImageStepsSliceDefaultPrimaryImagesItem>
  >;

  /**
   * Steps field in *ProcessWithImageSteps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_with_image_steps.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<
    Simplify<ProcessWithImageStepsSliceDefaultPrimaryStepsItem>
  >;
}

/**
 * Default variation for ProcessWithImageSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Each step displays an image on the left with a heading and description on the right in a vertical list.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessWithImageStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessWithImageStepsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProcessWithImageSteps*
 */
type ProcessWithImageStepsSliceVariation = ProcessWithImageStepsSliceDefault;

/**
 * ProcessWithImageSteps Shared Slice
 *
 * - **API ID**: `process_with_image_steps`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessWithImageStepsSlice = prismic.SharedSlice<
  "process_with_image_steps",
  ProcessWithImageStepsSliceVariation
>;

/**
 * Item in *ProjectSummaryShowcase → Default with Features & Image → Primary → Features*
 */
export interface ProjectSummaryShowcaseSliceDefaultWithFeaturesImagePrimaryFeaturesItem {
  /**
   * Icon field in *ProjectSummaryShowcase → Default with Features & Image → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Text field in *ProjectSummaryShowcase → Default with Features & Image → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.features[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectSummaryShowcase → Default with Features & Image → Primary*
 */
export interface ProjectSummaryShowcaseSliceDefaultWithFeaturesImagePrimary {
  /**
   * Eyebrow field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow: prismic.RichTextField;

  /**
   * Main Title field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.main_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_title: prismic.RichTextField;

  /**
   * Subtitle field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Summary Title field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.summary_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary_title: prismic.RichTextField;

  /**
   * Summary Text field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.summary_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary_text: prismic.RichTextField;

  /**
   * Primary Button field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.primary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Features field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<ProjectSummaryShowcaseSliceDefaultWithFeaturesImagePrimaryFeaturesItem>
  >;

  /**
   * Preview Image field in *ProjectSummaryShowcase → Default with Features & Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_summary_showcase.default_with_features_image.primary.preview_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  preview_image: prismic.ImageField<never>;
}

/**
 * Default with Features & Image variation for ProjectSummaryShowcase Slice
 *
 * - **API ID**: `default_with_features_image`
 * - **Description**: Features a summary area, feature icon list, CTA button, and a large image or embed for showcasing the final product.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSummaryShowcaseSliceDefaultWithFeaturesImage =
  prismic.SharedSliceVariation<
    "default_with_features_image",
    Simplify<ProjectSummaryShowcaseSliceDefaultWithFeaturesImagePrimary>,
    never
  >;

/**
 * Slice variation for *ProjectSummaryShowcase*
 */
type ProjectSummaryShowcaseSliceVariation =
  ProjectSummaryShowcaseSliceDefaultWithFeaturesImage;

/**
 * ProjectSummaryShowcase Shared Slice
 *
 * - **API ID**: `project_summary_showcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSummaryShowcaseSlice = prismic.SharedSlice<
  "project_summary_showcase",
  ProjectSummaryShowcaseSliceVariation
>;

/**
 * Item in *ProjectsGrid → Default → Primary → Items*
 */
export interface ProjectsGridSliceDefaultPrimaryItemsItem {
  /**
   * Curated Projects field in *ProjectsGrid → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.default.primary.items[].curated_projects
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  curated_projects: ContentRelationshipFieldWithData<
    [
      {
        id: "project_post";
        fields: [
          "project_title",
          "excerpt",
          "project_date",
          "client_name",
          "featured",
          "meta_title",
          "meta_description",
          "meta_image",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *ProjectsGrid → Default → Primary*
 */
export interface ProjectsGridSliceDefaultPrimary {
  /**
   * Mode field in *ProjectsGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.default.primary.mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  mode: prismic.SelectField<"dynamic" | "curated">;

  /**
   * Page Size field in *ProjectsGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.default.primary.page_size
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  page_size: prismic.NumberField;

  /**
   * Items field in *ProjectsGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ProjectsGridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ProjectsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectsGrid*
 */
type ProjectsGridSliceVariation = ProjectsGridSliceDefault;

/**
 * ProjectsGrid Shared Slice
 *
 * - **API ID**: `projects_grid`
 * - **Description**: ProjectsGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsGridSlice = prismic.SharedSlice<
  "projects_grid",
  ProjectsGridSliceVariation
>;

/**
 * Item in *ServicesCarousel → Default → Primary → Items*
 */
export interface ServicesCarouselSliceDefaultPrimaryItemsItem {
  /**
   * Service Ref field in *ServicesCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: services_carousel.default.primary.items[].service_ref
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  service_ref: ContentRelationshipFieldWithData<
    [
      {
        id: "service_card";
        fields: [
          "title",
          "summary",
          {
            id: "color";
            customtypes: [{ id: "brand_color"; fields: ["name", "value"] }];
          },
          "link",
        ];
      },
    ]
  >;

  /**
   * Highlight field in *ServicesCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: services_carousel.default.primary.items[].highlight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight: prismic.BooleanField;
}

/**
 * Primary content in *ServicesCarousel → Default → Primary*
 */
export interface ServicesCarouselSliceDefaultPrimary {
  /**
   * Section Title field in *ServicesCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_carousel.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Items field in *ServicesCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_carousel.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ServicesCarouselSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ServicesCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesCarousel*
 */
type ServicesCarouselSliceVariation = ServicesCarouselSliceDefault;

/**
 * ServicesCarousel Shared Slice
 *
 * - **API ID**: `services_carousel`
 * - **Description**: ServicesCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesCarouselSlice = prismic.SharedSlice<
  "services_carousel",
  ServicesCarouselSliceVariation
>;

/**
 * Primary content in *SplitContent → Default → Primary*
 */
export interface SplitContentSliceDefaultPrimary {
  /**
   * Heading field in *SplitContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_content.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *SplitContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for SplitContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Left side contains a heading, right side contains a flexible rich text area for detailed description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SplitContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SplitContent*
 */
type SplitContentSliceVariation = SplitContentSliceDefault;

/**
 * SplitContent Shared Slice
 *
 * - **API ID**: `split_content`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SplitContentSlice = prismic.SharedSlice<
  "split_content",
  SplitContentSliceVariation
>;

/**
 * Primary content in *TestimonialWithAvatar → Default → Primary*
 */
export interface TestimonialWithAvatarSliceDefaultPrimary {
  /**
   * Quote field in *TestimonialWithAvatar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_with_avatar.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Avatar field in *TestimonialWithAvatar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_with_avatar.default.primary.avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Author Name field in *TestimonialWithAvatar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_with_avatar.default.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Role field in *TestimonialWithAvatar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_with_avatar.default.primary.author_role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author Company field in *TestimonialWithAvatar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_with_avatar.default.primary.author_company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_company: prismic.KeyTextField;

  /**
   * Background Color field in *TestimonialWithAvatar → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_with_avatar.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    | "Cactus Green"
    | "Sunset Yellow"
    | "Magenta"
    | "Turquoise"
    | "Dark Brown"
    | "Blue"
  >;
}

/**
 * Default variation for TestimonialWithAvatar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default testimonial layout with avatar, quote, author name, role, and customizable decorative accents.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialWithAvatarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialWithAvatarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialWithAvatar*
 */
type TestimonialWithAvatarSliceVariation = TestimonialWithAvatarSliceDefault;

/**
 * TestimonialWithAvatar Shared Slice
 *
 * - **API ID**: `testimonial_with_avatar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialWithAvatarSlice = prismic.SharedSlice<
  "testimonial_with_avatar",
  TestimonialWithAvatarSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Items*
 */
export interface TestimonialsSliceDefaultPrimaryItemsItem {
  /**
   * Testimonial field in *Testimonials → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  testimonial: ContentRelationshipFieldWithData<
    [
      {
        id: "testimonial";
        fields: [
          "quote",
          "author_name",
          "avatar",
          {
            id: "color";
            customtypes: [{ id: "brand_color"; fields: ["name", "value"] }];
          },
          "company",
          "rating",
          "featured",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Background Color field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  background_color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Section Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Items field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Testimonials → Auto → Primary*
 */
export interface TestimonialsSliceAutoPrimary {
  /**
   * Background Color field in *Testimonials → Auto → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.auto.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  background_color: ContentRelationshipFieldWithData<
    [{ id: "brand_color"; fields: ["name", "value"] }]
  >;

  /**
   * Section Title field in *Testimonials → Auto → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.auto.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Limit field in *Testimonials → Auto → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.auto.primary.limit
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  limit: prismic.NumberField;

  /**
   * Order field in *Testimonials → Auto → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Newest
   * - **API ID Path**: testimonials.auto.primary.order
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  order: prismic.SelectField<"Newest" | "Random", "filled">;
}

/**
 * Auto variation for Testimonials Slice
 *
 * - **API ID**: `auto`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceAuto = prismic.SharedSliceVariation<
  "auto",
  Simplify<TestimonialsSliceAutoPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation =
  | TestimonialsSliceDefault
  | TestimonialsSliceAuto;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      BrandColorDocument,
      BrandColorDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataNavLinksItem,
      FooterDocumentDataSocialItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ProjectPostDocument,
      ProjectPostDocumentData,
      ProjectPostDocumentDataSlicesSlice,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      ServiceCardDocument,
      ServiceCardDocumentData,
      ServicePostDocument,
      ServicePostDocumentData,
      ServicePostDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      TechnologyDocument,
      TechnologyDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      FaqWithHeadingSlice,
      FaqWithHeadingSliceDefaultPrimaryFaqItemsItem,
      FaqWithHeadingSliceDefaultPrimary,
      FaqWithHeadingSliceVariation,
      FaqWithHeadingSliceDefault,
      FeaturedProjectsSlice,
      FeaturedProjectsSliceDefaultPrimary,
      FeaturedProjectsSliceVariation,
      FeaturedProjectsSliceDefault,
      HeadlineCtaCenteredSlice,
      HeadlineCtaCenteredSliceDefaultPrimary,
      HeadlineCtaCenteredSliceVariation,
      HeadlineCtaCenteredSliceDefault,
      HeadlineCtaIntroSlice,
      HeadlineCtaIntroSliceDefaultPrimary,
      HeadlineCtaIntroSliceVariation,
      HeadlineCtaIntroSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroPixelArtSlice,
      HeroPixelArtSliceDefaultPrimary,
      HeroPixelArtSliceVariation,
      HeroPixelArtSliceDefault,
      HeroShowcaseSlice,
      HeroShowcaseSliceWithComparisonVisualPrimaryTechStackItem,
      HeroShowcaseSliceWithComparisonVisualPrimary,
      HeroShowcaseSliceVariation,
      HeroShowcaseSliceWithComparisonVisual,
      ImageCarouselSlice,
      ImageCarouselSliceDefaultPrimarySlidesItem,
      ImageCarouselSliceDefaultPrimary,
      ImageCarouselSliceVariation,
      ImageCarouselSliceDefault,
      PeopleSlice,
      PeopleSliceDefaultPrimary,
      PeopleSliceVariation,
      PeopleSliceDefault,
      ProcessWithImageStepsSlice,
      ProcessWithImageStepsSliceDefaultPrimaryImagesItem,
      ProcessWithImageStepsSliceDefaultPrimaryStepsItem,
      ProcessWithImageStepsSliceDefaultPrimary,
      ProcessWithImageStepsSliceVariation,
      ProcessWithImageStepsSliceDefault,
      ProjectSummaryShowcaseSlice,
      ProjectSummaryShowcaseSliceDefaultWithFeaturesImagePrimaryFeaturesItem,
      ProjectSummaryShowcaseSliceDefaultWithFeaturesImagePrimary,
      ProjectSummaryShowcaseSliceVariation,
      ProjectSummaryShowcaseSliceDefaultWithFeaturesImage,
      ProjectsGridSlice,
      ProjectsGridSliceDefaultPrimaryItemsItem,
      ProjectsGridSliceDefaultPrimary,
      ProjectsGridSliceVariation,
      ProjectsGridSliceDefault,
      ServicesCarouselSlice,
      ServicesCarouselSliceDefaultPrimaryItemsItem,
      ServicesCarouselSliceDefaultPrimary,
      ServicesCarouselSliceVariation,
      ServicesCarouselSliceDefault,
      SplitContentSlice,
      SplitContentSliceDefaultPrimary,
      SplitContentSliceVariation,
      SplitContentSliceDefault,
      TestimonialWithAvatarSlice,
      TestimonialWithAvatarSliceDefaultPrimary,
      TestimonialWithAvatarSliceVariation,
      TestimonialWithAvatarSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryItemsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceAutoPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TestimonialsSliceAuto,
    };
  }
}
