// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  faq_with_heading: dynamic(() => import("./FaqWithHeading")),
  featured_projects: dynamic(() => import("./FeaturedProjects")),
  headline_cta_centered: dynamic(() => import("./HeadlineCtaCentered")),
  headline_cta_intro: dynamic(() => import("./HeadlineCtaIntro")),
  hero: dynamic(() => import("./Hero")),
  hero_pixel_art: dynamic(() => import("./HeroPixelArt")),
  hero_showcase: dynamic(() => import("./HeroShowcase")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  people: dynamic(() => import("./People")),
  process_with_image_steps: dynamic(() => import("./ProcessWithImageSteps")),
  project_summary_showcase: dynamic(() => import("./ProjectSummaryShowcase")),
  projects_grid: dynamic(() => import("./ProjectsGrid")),
  services_carousel: dynamic(() => import("./ServicesCarousel")),
  show_case_split: dynamic(() => import("./ShowCaseSplit")),
  split_content: dynamic(() => import("./SplitContent")),
  testimonial_with_avatar: dynamic(() => import("./TestimonialWithAvatar")),
  testimonials: dynamic(() => import("./Testimonials")),
};
