// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  card: dynamic(() => import("./Card")),
  hero: dynamic(() => import("./Hero")),
  people: dynamic(() => import("./People")),
};
